version: '3.8'
services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: bimm_xml_api_container
    volumes:
      - ./app
    ports:
        - '3000:3000'
  db:
    image: mongo:latest
    container_name: bimm_xml_container
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=${}
      - MONGO_INITDB_ROOT_USERNAME=${}
      - MONGO_INITDB_ROOT_PASSWORD=${}
    volumes:
      - ./home/mongodb:/home/mongodb
      - mongodbdata:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - '27017-27019:27017-27019'

volumes:
  mongodbdata:
    driver: local